# Generated by Django 4.1.4 on 2023-01-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_demand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Название по умолчанию', max_length=50, verbose_name='Название')),
                ('full_text', models.TextField(verbose_name='Текст')),
                ('photo', models.ImageField(upload_to='static/photos')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'География',
                'verbose_name_plural': 'География',
            },
        ),
        migrations.AlterModelOptions(
            name='demand',
            options={'verbose_name': 'Востребованность', 'verbose_name_plural': 'Востребованность'},
        ),
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'Главная', 'verbose_name_plural': 'Главная'},
        ),
    ]
